### ISSUE TITLE
Error messages while creating service templates

### ISSUE THREAD

**Issue by ottorei** [librenms/librenms#12536]
Creating a service template seems to always fail either on the form itself or with a PHP stacktrace. With the form itself, using dynamic groups seems to lead into the following error message with any possible values selected. When saving the form, the data is reset and the following messages are shown:

![templates1](https://user-images.githubusercontent.com/7031571/107949015-4bf79f00-6f9d-11eb-9d4a-663a6bcf9da8.PNG)
![templates2](https://user-images.githubusercontent.com/7031571/107949092-6c275e00-6f9d-11eb-9494-39cef2be5dd0.PNG)

If using static Device Groups:
![templates4](https://user-images.githubusercontent.com/7031571/107949582-2919ba80-6f9e-11eb-9858-3a2932696a3a.PNG)

POST data:
![templates5](https://user-images.githubusercontent.com/7031571/108135875-92deb500-70c1-11eb-82b5-40b76b9df1ae.PNG)

PHP stacktrace:
https://paste.ubuntu.com/p/j8J4VdZG8g/

**Comment by loxybjorn** [comment]
The same issue, as far as I can see, is registered in [the LibreNMS Community forums](https://community.librenms.org/t/error-creating-new-service-template/14885/2).

**Comment by murrant** [comment]
Original author is unable to look into this in the near future.  I welcome a fix if anyone wants to look into this.

**Comment by si458** [comment]
ill tag onto this and im having the same issue,
i even get a 500 error when trying to create a service template using static instead of dynamic

**Comment by murrant** [comment]
Fixed

**Comment by si458** [comment]
@murrant what PR was this to fix this issue as im still getting error 500 ?
