### ISSUE TITLE
Addition of enLogic EN2.0 PDUs #18094 seams to have broken discovery of older nLogic PDUs

### ISSUE THREAD

**Issue by loqster** [librenms/librenms#18243]
### The problem

After the last updated to version 25.8.0. most of our nLogic PDUs changed from being discovered to 'generic' devices. 

I'm not a coder so it is difficult to determine what change caused this exactly but it might have something to do with the PR in the title relating to the addition of nLogic EN2.0 PDUs

The new nLogic PDUs that we have work fine and discovery on them works without issues. 

When / If needed I can run tests and provide more details of devices I have a LAB deployment that can be experimented on.

The Attached files are the outputs requested the only thing done was to replace the PDU IP with a.b.c.d

### Output of ./validate.php

```txt
/opt/librenms $ ./validate.php 
===========================================
Component | Version
--------- | -------
LibreNMS  | 25.8.0 (2025-08-20T18:11:01+01:00)
DB Schema | 2025_07_10_201918_update_vlans_table (353)
PHP       | 8.3.24
Python    | 3.12.11
Database  | MariaDB 10.11.14-MariaDB-ubu2204
RRDTool   | 1.9.0
SNMP      | 5.9.4
===========================================

[OK]    Installed from the official Docker image; no Composer required
[OK]    Database Connected
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    No python wrapper pollers found
[OK]    Redis is functional
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
[WARN]  Updates are managed through the official Docker image
```

### What was the last working version of LibreNMS?

25.7.0

### Device info

nLogic / OS Version: 7.12R39 / Hardware: EN1113

### Discovery output

```txt
/opt/librenms $ ./discovery.php -h 3
LibreNMS Discovery
a.b.c.d 3 generic 
#### Load disco module core ####
OS: Generic Device (generic)
  

>> Runtime for discovery module 'core': 0.2000 seconds with 86840 bytes
>> SNMP: [4/0.16s] MySQL: [0/0.00s] RRD: [0/0.00s]  
#### Unload disco module core ####


#### Load disco module os ####
Location: 1-47  
Hardware:   
OS Version:   
OS Features:   
Serial:   

>> Runtime for discovery module 'os': 0.1270 seconds with 184384 bytes
>> SNMP: [4/0.09s] MySQL: [1/0.01s] RRD: [0/0.00s]  
#### Unload disco module os ####


#### Load disco module ports ####
.

>> Runtime for discovery module 'ports': 0.1950 seconds with 5336 bytes
>> SNMP: [5/0.19s] MySQL: [2/0.02s] RRD: [0/0.00s]  
#### Unload disco module ports ####


#### Load disco module ports-stack ####

>> Runtime for discovery module 'ports-stack': 0.0490 seconds with 848 bytes
>> SNMP: [1/0.05s] MySQL: [0/0.00s] RRD: [0/0.00s]  
#### Unload disco module ports-stack ####

Module [ xdsl ] disabled globally.


#### Load disco module entity-physical ####

>> Runtime for discovery module 'entity-physical': 0.0520 seconds with 71176 bytes
>> SNMP: [1/0.05s] MySQL: [1/0.01s] RRD: [0/0.00s]  
#### Unload disco module entity-physical ####

Module [ entity-state ] disabled globally.

Module [ isis ] disabled globally.


#### Load disco module processors ####
Host Resources:   
UCD Resources:   


>> Runtime for discovery module 'processors': 0.1150 seconds with 41536 bytes
>> SNMP: [2/0.09s] MySQL: [2/0.02s] RRD: [0/0.00s]  
#### Unload disco module processors ####


#### Load disco module mempools ####
  

>> Runtime for discovery module 'mempools': 0.1160 seconds with 72616 bytes
>> SNMP: [2/0.11s] MySQL: [1/0.01s] RRD: [0/0.00s]  
#### Unload disco module mempools ####

Module [ cisco-vrf-lite ] disabled globally.

Module [ cisco-mac-accounting ] disabled globally.

Module [ cisco-pw ] disabled globally.

Module [ vrf ] disabled globally.


#### Load disco module ospfv3 ####
Processes: 
>> Runtime for discovery module 'ospfv3': 0.0610 seconds with 19288 bytes
>> SNMP: [1/0.05s] MySQL: [1/0.01s] RRD: [0/0.00s]  
#### Unload disco module ospfv3 ####

Module [ cisco-cef ] disabled globally.

Module [ slas ] disabled globally.

Module [ cisco-otv ] disabled globally.

Module [ cisco-qfp ] disabled globally.


#### Load disco module ipv4-addresses ####
.
>> Runtime for discovery module 'ipv4-addresses': 0.1590 seconds with 91784 bytes
>> SNMP: [3/0.14s] MySQL: [3/0.03s] RRD: [0/0.00s]  
#### Unload disco module ipv4-addresses ####


#### Load disco module ipv6-addresses ####

>> Runtime for discovery module 'ipv6-addresses': 0.1500 seconds with 77424 bytes
>> SNMP: [3/0.14s] MySQL: [1/0.01s] RRD: [0/0.00s]  
#### Unload disco module ipv6-addresses ####


#### Load disco module qos ####

>> Runtime for discovery module 'qos': 0.0010 seconds with 144 bytes
>> SNMP: [0/0.00s] MySQL: [0/0.00s] RRD: [0/0.00s]  
#### Unload disco module qos ####

Module [ route ] disabled globally.


#### Load disco module transceivers ####

>> Runtime for discovery module 'transceivers': 0.0000 seconds with 160 bytes
>> SNMP: [0/0.00s] MySQL: [0/0.00s] RRD: [0/0.00s]  
#### Unload disco module transceivers ####


#### Load disco module sensors ####
 ENTITY-SENSOR: Caching OIDs: entPhysicalDescr
Airflow: 
Ber: 
Bitrate: 
Charge: 
Chromatic_dispersion: 
Cooling: 
Count: 
Current: 
Dbm: 
Delay: 
Eer: 
Fanspeed: 
Frequency: 
Humidity: 
Load: 
Loss: 
Percent: 
Power: 
Power_consumed: 
Power_factor: 
Pressure: 
Quality_factor: 
Runtime: 
Signal: 
Snr: 
State: 
Temperature: 
Tv_signal: 
Voltage: 
Waterflow: 

>> Runtime for discovery module 'sensors': 0.0620 seconds with 7968 bytes
>> SNMP: [1/0.04s] MySQL: [1/0.01s] RRD: [0/0.00s]  
#### Unload disco module sensors ####


#### Load disco module storage ####
  

>> Runtime for discovery module 'storage': 0.0470 seconds with 3472 bytes
>> SNMP: [1/0.04s] MySQL: [1/0.01s] RRD: [0/0.00s]  
#### Unload disco module storage ####


#### Load disco module hr-device ####

>> Runtime for discovery module 'hr-device': 0.0980 seconds with 7312 bytes
>> SNMP: [2/0.09s] MySQL: [1/0.01s] RRD: [0/0.00s]  
#### Unload disco module hr-device ####


#### Load disco module discovery-protocols ####
 LLDP-MIB:  LLDP-V2-MIB: 
 OSPF Discovery: 
 OSPFv3 Discovery: 

>> Runtime for discovery module 'discovery-protocols': 0.1260 seconds with 9872 bytes
>> SNMP: [2/0.11s] MySQL: [4/0.04s] RRD: [0/0.00s]  
#### Unload disco module discovery-protocols ####


#### Load disco module arp-table ####
.
>> Runtime for discovery module 'arp-table': 0.1000 seconds with 8064 bytes
>> SNMP: [2/0.09s] MySQL: [1/0.01s] RRD: [0/0.00s]  
#### Unload disco module arp-table ####


#### Load disco module ipv6-nd ####

>> Runtime for discovery module 'ipv6-nd': 0.0040 seconds with 69856 bytes
>> SNMP: [0/0.00s] MySQL: [1/0.01s] RRD: [0/0.00s]  
#### Unload disco module ipv6-nd ####

Module [ discovery-arp ] disabled globally.

Module [ junose-atm-vp ] disabled globally.


#### Load disco module bgp-peers ####
No BGP on host

>> Runtime for discovery module 'bgp-peers': 0.0490 seconds with 1880 bytes
>> SNMP: [1/0.04s] MySQL: [3/0.03s] RRD: [0/0.00s]  
#### Unload disco module bgp-peers ####


#### Load disco module vlans ####
VLANs: 
VLAN Ports: 

>> Runtime for discovery module 'vlans': 0.3260 seconds with 13304 bytes
>> SNMP: [5/0.32s] MySQL: [2/0.02s] RRD: [0/0.00s]  
#### Unload disco module vlans ####

Module [ vminfo ] disabled globally.

Module [ printer-supplies ] disabled globally.


#### Load disco module ucd-diskio ####

>> Runtime for discovery module 'ucd-diskio': 0.0450 seconds with 4296 bytes
>> SNMP: [1/0.04s] MySQL: [1/0.01s] RRD: [0/0.00s]  
#### Unload disco module ucd-diskio ####

Module [ applications ] disabled globally.


#### Load disco module services ####

>> Runtime for discovery module 'services': 0.0000 seconds with 80 bytes
>> SNMP: [0/0.00s] MySQL: [0/0.00s] RRD: [0/0.00s]  
#### Unload disco module services ####


#### Load disco module stp ####
Instances: 
Ports: 

>> Runtime for discovery module 'stp': 0.0410 seconds with 9032 bytes
>> SNMP: [1/0.03s] MySQL: [2/0.02s] RRD: [0/0.00s]  
#### Unload disco module stp ####


#### Load disco module ntp ####

>> Runtime for discovery module 'ntp': 0.0000 seconds with 80 bytes
>> SNMP: [0/0.00s] MySQL: [0/0.00s] RRD: [0/0.00s]  
#### Unload disco module ntp ####

Module [ loadbalancers ] disabled globally.

Module [ mef ] disabled globally.


#### Load disco module wireless ####

>> Runtime for discovery module 'wireless': 0.0150 seconds with 5696 bytes
>> SNMP: [0/0.00s] MySQL: [1/0.01s] RRD: [0/0.00s]  
#### Unload disco module wireless ####


#### Load disco module fdb-table ####


>> Runtime for discovery module 'fdb-table': 0.0940 seconds with 5184 bytes
>> SNMP: [0/0.00s] MySQL: [2/0.02s] RRD: [0/0.00s]  
#### Unload disco module fdb-table ####


#### Load disco module mpls ####

>> Runtime for discovery module 'mpls': 0.0020 seconds with 65680 bytes
>> SNMP: [0/0.00s] MySQL: [0/0.00s] RRD: [0/0.00s]  
#### Unload disco module mpls ####

Discovered in 3.396 seconds


SNMP [43/1.94s]: Snmpget[14/0.54s] Snmpwalk[29/1.40s]  
SQL [36/0.47s]: Select[30/0.32s] Update[2/0.11s] Delete[4/0.03s]  
RRD [0/0.00s]:
```

### Poller output

```txt
/opt/librenms $ lnms device:poll 3 -vv --no-data
SQL[select `migration` from `migrations` order by `id` desc limit 1 [] 0.78ms] 
  
SQL[select count(*) as aggregate from `migrations` [] 0.87ms] 
  
SQL[select version() [] 0.5ms] 
  
===========================================
Component | Version
--------- | -------
LibreNMS  | 25.8.0 (2025-08-20T18:11:01+01:00)
DB Schema | 2025_07_10_201918_update_vlans_table (353)
PHP       | 8.3.24
Python    | 3.12.11
Database  | MariaDB 10.11.14-MariaDB-ubu2204
RRDTool   | 1.9.0
SNMP      | 5.9.4
===========================================
  
LibreNMS config cache cleared and config reloaded.  
SQL[select `config_name`, `config_value` from `config` [] 0.88ms] 
  
SQL[select * from `graph_types` [] 0.53ms] 
  
Starting polling run:

SQL[select `device_id` from `devices` where `device_id` = ? ["3"] 0.84ms] 
  
SQL[select * from `devices` where `device_id` = ? limit 1 [3] 1.35ms] 
  
Hostname:  a.b.c.d  
ID:        3
OS:        generic
IP:        a.b.c.d
  
Attempting to initialize OS: generic  
OS initialized: LibreNMS\OS\Generic  
SQL[select * from `devices_attribs` where `devices_attribs`.`device_id` = ? and `devices_attribs`.`device_id` is not null [3] 0.98ms] 
  
[FPING] '/usr/sbin/fping' '-e' '-q' '-c' '3' '-p' '500' '-t' '500' '-O' '0' 'a.b.c.d'
  
response: a.b.c.d : xmt/rcv/%loss = 3/3/0%, min/avg/max = 0.35/0.403/0.444  
SNMP['/usr/bin/snmpget' '-M' '/opt/librenms/mibs' '-m' 'SNMPv2-TC:SNMPv2-MIB:IF-MIB:IP-MIB:TCP-MIB:UDP-MIB:NET-SNMP-VACM-MIB' '-v2c' '-c' 'COMMUNITY' '-OQXUte' '-Pu' 'udp:HOSTNAME:161' 'SNMPv2-MIB::sysObjectID.0']  
SNMPv2-MIB::sysObjectID.0 = SNMPv2-SMI::enterprises.38446.1
  
  
SQL[update `devices` set `last_ping` = ?, `last_ping_timetaken` = ? where `device_id` = ? ["2025-09-12 10:48:13",0.403,3] 3.92ms] 
  
RRD[update /data/rrd/a.b.c.d/icmp-perf.rrd N:0.403:3:3:0.35:0.444]  
SQL[select * from `device_outages` where `device_outages`.`device_id` = ? and `device_outages`.`device_id` is not null and `up_again` is null [3] 1.05ms] 
  
#### Load poller module core ####
  
Module enabled: Global + | OS   | Device   | Manual    
SNMP['/usr/bin/snmpget' '-M' '/opt/librenms/mibs' '-m' 'SNMPv2-TC:SNMPv2-MIB:IF-MIB:IP-MIB:TCP-MIB:UDP-MIB:NET-SNMP-VACM-MIB' '-v2c' '-c' 'COMMUNITY' '-OQXUte' '-Pu' '-On' 'udp:HOSTNAME:161' 'SNMPv2-MIB::sysUpTime.0']  
.*.*.0 = 238162827
  
  
SNMP['/usr/bin/snmpget' '-M' '/opt/librenms/mibs' '-m' 'SNMPv2-TC:SNMPv2-MIB:IF-MIB:IP-MIB:TCP-MIB:UDP-MIB:NET-SNMP-VACM-MIB' '-v2c' '-c' 'COMMUNITY' '-OQXUte' '-Pu' 'udp:HOSTNAME:161' 'SNMP-FRAMEWORK-MIB::snmpEngineTime.0' 'HOST-RESOURCES-MIB::hrSystemUptime.0']  
Exitcode: 2 ["Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: SNMP-FRAMEWORK-MIB::snmpEngineTime.0

Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: HOST-RESOURCES-MIB::hrSystemUptime.0

"] 
  
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: SNMP-FRAMEWORK-MIB::snmpEngineTime.0

Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: HOST-RESOURCES-MIB::hrSystemUptime.0

  
Uptime seconds: 2381628
  
RRD[update /data/rrd/a.b.c.d/uptime.rrd N:2381628]  
Uptime: 3 weeks 6 days 13 hours 33 minutes  
SQL[update `devices` set `uptime` = ? where `device_id` = ? [2381628,3] 4.18ms] 
  
  
>> SNMP: [3/0.14s] MySQL: [4/0.10s] RRD: [2/0.00s]  
>> Runtime for poller module 'core': 0.1109 seconds with 109712 bytes  
RRD[update /data/rrd/a.b.c.d/poller-perf-core.rrd N:0.11086392402649]  
#### Unload poller module core ####
  
#### Load poller module os ####
  
Module enabled: Global + | OS   | Device   | Manual    
SQL[select * from `locations` where `locations`.`id` = ? limit 1 [1] 0.9ms] 
  
Location: 1-47  
Hardware:   
OS Version:   
OS Features:   
Serial:   
  
>> SNMP: [0/0.00s] MySQL: [1/0.01s] RRD: [1/0.00s]  
>> Runtime for poller module 'os': 0.0123 seconds with 17256 bytes  
RRD[update /data/rrd/a.b.c.d/poller-perf-os.rrd N:0.012286186218262]  
#### Unload poller module os ####
  
#### Load poller module availability ####
  
Module enabled: Global + | OS   | Device   | Manual    
SQL[select * from `device_outages` where `device_outages`.`device_id` = ? and `device_outages`.`device_id` is not null and `up_again` >= ? order by `going_down` asc [3,1757584093] 0.91ms] 
  
SQL[select * from `availability` where (`device_id` = ? and `duration` = ?) limit 1 [3,86400] 0.84ms] 
  
SQL[update `availability` set `availability_perc` = ? where `availability_id` = ? [100,9] 0.73ms] 
  
RRD[update /data/rrd/a.b.c.d/availability-86400.rrd N:100]  
1 day   : 100%  
SQL[select * from `device_outages` where `device_outages`.`device_id` = ? and `device_outages`.`device_id` is not null and `up_again` >= ? order by `going_down` asc [3,1757065693] 1.2ms] 
  
SQL[select * from `availability` where (`device_id` = ? and `duration` = ?) limit 1 [3,604800] 0.8ms] 
  
SQL[update `availability` set `availability_perc` = ? where `availability_id` = ? [100,10] 0.67ms] 
  
RRD[update /data/rrd/a.b.c.d/availability-604800.rrd N:100]  
1 week  : 100%  
SQL[select * from `device_outages` where `device_outages`.`device_id` = ? and `device_outages`.`device_id` is not null and `up_again` >= ? order by `going_down` asc [3,1755078493] 0.8ms] 
  
SQL[select * from `availability` where (`device_id` = ? and `duration` = ?) limit 1 [3,2592000] 0.73ms] 
  
SQL[update `availability` set `availability_perc` = ? where `availability_id` = ? [100,11] 0.64ms] 
  
RRD[update /data/rrd/a.b.c.d/availability-2592000.rrd N:100]  
4 weeks : 100%  
SQL[select * from `device_outages` where `device_outages`.`device_id` = ? and `device_outages`.`device_id` is not null and `up_again` >= ? order by `going_down` asc [3,1726134493] 0.81ms] 
  
SQL[select * from `availability` where (`device_id` = ? and `duration` = ?) limit 1 [3,31536000] 0.69ms] 
  
SQL[update `availability` set `availability_perc` = ? where `availability_id` = ? [100,12] 0.61ms] 
  
RRD[update /data/rrd/a.b.c.d/availability-31536000.rrd N:100]  
1 year  : 100%  
SQL[delete from `availability` where `availability`.`device_id` = ? and `availability`.`device_id` is not null and `availability_id` not in (?, ?, ?, ?) [3,9,10,11,12] 0.64ms] 
  
  
>> SNMP: [0/0.00s] MySQL: [13/0.10s] RRD: [5/0.00s]  
>> Runtime for poller module 'availability': 0.0346 seconds with 85064 bytes  
RRD[update /data/rrd/a.b.c.d/poller-perf-availability.rrd N:0.034631013870239]  
#### Unload poller module availability ####
  
#### Load poller module ipmi ####
  
Module enabled: Global + | OS   | Device   | Manual    
SQL[SELECT * FROM sensors WHERE device_id = ? AND poller_type='ipmi' [3] 0.97ms] 
  
array (
)  
  
>> SNMP: [0/0.00s] MySQL: [1/0.01s] RRD: [1/0.00s]  
>> Runtime for poller module 'ipmi': 0.0073 seconds with 2184 bytes  
RRD[update /data/rrd/a.b.c.d/poller-perf-ipmi.rrd N:0.0072958469390869]  
#### Unload poller module ipmi ####
  
#### Load poller module sensors ####
  
Module enabled: Global + | OS   | Device   | Manual    
SQL[SELECT `sensor_class` FROM `sensors` WHERE `device_id` = ? GROUP BY `sensor_class` [3] 0.81ms] 
  
  
>> SNMP: [0/0.00s] MySQL: [1/0.01s] RRD: [1/0.00s]  
>> Runtime for poller module 'sensors': 0.0035 seconds with 2376 bytes  
RRD[update /data/rrd/a.b.c.d/poller-perf-sensors.rrd N:0.0035099983215332]  
#### Unload poller module sensors ####
  
#### Load poller module processors ####
  
Module enabled: Global + | OS   | Device   | Manual    
Attempting to initialize OS: generic  
OS initialized: LibreNMS\OS\Generic  
SQL[SELECT * FROM processors WHERE device_id=? [3] 0.9ms] 
  
  
>> SNMP: [0/0.00s] MySQL: [1/0.01s] RRD: [1/0.00s]  
>> Runtime for poller module 'processors': 0.0069 seconds with 2640 bytes  
RRD[update /data/rrd/a.b.c.d/poller-perf-processors.rrd N:0.0069379806518555]  
#### Unload poller module processors ####
  
#### Load poller module mempools ####
  
Module enabled: Global + | OS   | Device   | Manual    
SQL[select * from `mempools` where `mempools`.`device_id` = ? and `mempools`.`device_id` is not null [3] 0.91ms] 
  
  
>> SNMP: [0/0.00s] MySQL: [1/0.01s] RRD: [1/0.00s]  
>> Runtime for poller module 'mempools': 0.0043 seconds with 2496 bytes  
RRD[update /data/rrd/a.b.c.d/poller-perf-mempools.rrd N:0.004345178604126]  
#### Unload poller module mempools ####
  
#### Load poller module storage ####
  
Module enabled: Global + | OS   | Device   | Manual    
SQL[select * from `storage` where `storage`.`device_id` = ? and `storage`.`device_id` is not null [3] 0.78ms] 
  
  
>> SNMP: [0/0.00s] MySQL: [1/0.01s] RRD: [1/0.00s]  
>> Runtime for poller module 'storage': 0.0038 seconds with 3480 bytes  
RRD[update /data/rrd/a.b.c.d/poller-perf-storage.rrd N:0.0038421154022217]  
#### Unload poller module storage ####
  
#### Load poller module netstats ####
  
Module enabled: Global + | OS   | Device   | Manual    
icmp   
SNMP['/usr/bin/snmpget' '-M' '/opt/librenms/mibs' '-m' 'SNMPv2-TC:SNMPv2-MIB:IF-MIB:IP-MIB:TCP-MIB:UDP-MIB:NET-SNMP-VACM-MIB' '-v2c' '-c' 'COMMUNITY' '-OQXUte' '-Pu' 'udp:HOSTNAME:161' 'IP-MIB::icmpInMsgs.0' 'IP-MIB::icmpOutMsgs.0' 'IP-MIB::icmpInErrors.0' 'IP-MIB::icmpOutErrors.0' 'IP-MIB::icmpInEchos.0' 'IP-MIB::icmpOutEchos.0' 'IP-MIB::icmpInEchoReps.0' 'IP-MIB::icmpOutEchoReps.0' 'IP-MIB::icmpInDestUnreachs.0' 'IP-MIB::icmpOutDestUnreachs.0']  
Exitcode: 2 ["Error in packet
Reason: (tooBig) Response message would have been too large.
Failed object: 
"] 
  
Error in packet
Reason: (tooBig) Response message would have been too large.
Failed object: 
  
SNMP['/usr/bin/snmpget' '-M' '/opt/librenms/mibs' '-m' 'SNMPv2-TC:SNMPv2-MIB:IF-MIB:IP-MIB:TCP-MIB:UDP-MIB:NET-SNMP-VACM-MIB' '-v2c' '-c' 'COMMUNITY' '-OQXUte' '-Pu' 'udp:HOSTNAME:161' 'IP-MIB::icmpInParmProbs.0' 'IP-MIB::icmpInTimeExcds.0' 'IP-MIB::icmpInSrcQuenchs.0' 'IP-MIB::icmpInRedirects.0' 'IP-MIB::icmpInTimestamps.0' 'IP-MIB::icmpInTimestampReps.0' 'IP-MIB::icmpInAddrMasks.0' 'IP-MIB::icmpInAddrMaskReps.0' 'IP-MIB::icmpOutTimeExcds.0' 'IP-MIB::icmpOutParmProbs.0']  
Exitcode: 2 ["Error in packet
Reason: (tooBig) Response message would have been too large.
Failed object: 
"] 
  
Error in packet
Reason: (tooBig) Response message would have been too large.
Failed object: 
  
SNMP['/usr/bin/snmpget' '-M' '/opt/librenms/mibs' '-m' 'SNMPv2-TC:SNMPv2-MIB:IF-MIB:IP-MIB:TCP-MIB:UDP-MIB:NET-SNMP-VACM-MIB' '-v2c' '-c' 'COMMUNITY' '-OQXUte' '-Pu' 'udp:HOSTNAME:161' 'IP-MIB::icmpOutSrcQuenchs.0' 'IP-MIB::icmpOutRedirects.0' 'IP-MIB::icmpOutTimestamps.0' 'IP-MIB::icmpOutTimestampReps.0' 'IP-MIB::icmpOutAddrMasks.0' 'IP-MIB::icmpOutAddrMaskReps.0']  
IP-MIB::icmpOutSrcQuenchs.0 = 0
IP-MIB::icmpOutRedirects.0 = 0
IP-MIB::icmpOutTimestamps.0 = 0
IP-MIB::icmpOutTimestampReps.0 = 0
IP-MIB::icmpOutAddrMasks.0 = 0
IP-MIB::icmpOutAddrMaskReps.0 = 0
  
  
RRD[update /data/rrd/a.b.c.d/netstats-icmp.rrd N:U:U:U:U:U:U:U:U:U:U:U:U:U:U:U:U:U:U:U:U:0:0:0:0:0:0]  
ip   
SNMP['/usr/bin/snmpget' '-M' '/opt/librenms/mibs' '-m' 'SNMPv2-TC:SNMPv2-MIB:IF-MIB:IP-MIB:TCP-MIB:UDP-MIB:NET-SNMP-VACM-MIB' '-v2c' '-c' 'COMMUNITY' '-OQXUte' '-Pu' 'udp:HOSTNAME:161' 'IP-MIB::ipForwDatagrams.0' 'IP-MIB::ipInDelivers.0' 'IP-MIB::ipInReceives.0' 'IP-MIB::ipOutRequests.0' 'IP-MIB::ipInDiscards.0' 'IP-MIB::ipOutDiscards.0' 'IP-MIB::ipOutNoRoutes.0' 'IP-MIB::ipReasmReqds.0' 'IP-MIB::ipReasmOKs.0' 'IP-MIB::ipReasmFails.0']  
Exitcode: 2 ["Error in packet
Reason: (tooBig) Response message would have been too large.
Failed object: 
"] 
  
Error in packet
Reason: (tooBig) Response message would have been too large.
Failed object: 
  
SNMP['/usr/bin/snmpget' '-M' '/opt/librenms/mibs' '-m' 'SNMPv2-TC:SNMPv2-MIB:IF-MIB:IP-MIB:TCP-MIB:UDP-MIB:NET-SNMP-VACM-MIB' '-v2c' '-c' 'COMMUNITY' '-OQXUte' '-Pu' 'udp:HOSTNAME:161' 'IP-MIB::ipFragOKs.0' 'IP-MIB::ipFragFails.0' 'IP-MIB::ipFragCreates.0' 'IP-MIB::ipInUnknownProtos.0' 'IP-MIB::ipInHdrErrors.0' 'IP-MIB::ipInAddrErrors.0']  
IP-MIB::ipFragOKs.0 = 0
IP-MIB::ipFragFails.0 = 0
IP-MIB::ipFragCreates.0 = 0
IP-MIB::ipInUnknownProtos.0 = 28
IP-MIB::ipInHdrErrors.0 = 0
IP-MIB::ipInAddrErrors.0 = 3253458
  
  
RRD[update /data/rrd/a.b.c.d/netstats-ip.rrd N:U:U:U:U:U:U:U:U:U:U:0:0:0:28:0:3253458]  
ip_forward   
SNMP['/usr/bin/snmpget' '-M' '/opt/librenms/mibs' '-m' 'SNMPv2-TC:SNMPv2-MIB:IF-MIB:IP-MIB:TCP-MIB:UDP-MIB:NET-SNMP-VACM-MIB' '-v2c' '-c' 'COMMUNITY' '-OQXUte' '-Pu' 'udp:HOSTNAME:161' 'IP-FORWARD-MIB::ipCidrRouteNumber.0']  
Exitcode: 2 ["Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: IP-FORWARD-MIB::ipCidrRouteNumber.0

"] 
  
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: IP-FORWARD-MIB::ipCidrRouteNumber.0

  
snmp   
SNMP['/usr/bin/snmpget' '-M' '/opt/librenms/mibs' '-m' 'SNMPv2-TC:SNMPv2-MIB:IF-MIB:IP-MIB:TCP-MIB:UDP-MIB:NET-SNMP-VACM-MIB' '-v2c' '-c' 'COMMUNITY' '-OQXUte' '-Pu' 'udp:HOSTNAME:161' 'SNMPv2-MIB::snmpInPkts.0' 'SNMPv2-MIB::snmpOutPkts.0' 'SNMPv2-MIB::snmpInBadVersions.0' 'SNMPv2-MIB::snmpInBadCommunityNames.0' 'SNMPv2-MIB::snmpInBadCommunityUses.0' 'SNMPv2-MIB::snmpInASNParseErrs.0' 'SNMPv2-MIB::snmpInTooBigs.0' 'SNMPv2-MIB::snmpInNoSuchNames.0' 'SNMPv2-MIB::snmpInBadValues.0' 'SNMPv2-MIB::snmpInReadOnlys.0']  
Exitcode: 2 ["Error in packet
Reason: (tooBig) Response message would have been too large.
Failed object: 
"] 
  
Error in packet
Reason: (tooBig) Response message would have been too large.
Failed object: 
  
SNMP['/usr/bin/snmpget' '-M' '/opt/librenms/mibs' '-m' 'SNMPv2-TC:SNMPv2-MIB:IF-MIB:IP-MIB:TCP-MIB:UDP-MIB:NET-SNMP-VACM-MIB' '-v2c' '-c' 'COMMUNITY' '-OQXUte' '-Pu' 'udp:HOSTNAME:161' 'SNMPv2-MIB::snmpInGenErrs.0' 'SNMPv2-MIB::snmpInTotalReqVars.0' 'SNMPv2-MIB::snmpInTotalSetVars.0' 'SNMPv2-MIB::snmpInGetRequests.0' 'SNMPv2-MIB::snmpInGetNexts.0' 'SNMPv2-MIB::snmpInSetRequests.0' 'SNMPv2-MIB::snmpInGetResponses.0' 'SNMPv2-MIB::snmpInTraps.0' 'SNMPv2-MIB::snmpOutTooBigs.0' 'SNMPv2-MIB::snmpOutNoSuchNames.0']  
Exitcode: 2 ["Error in packet
Reason: (tooBig) Response message would have been too large.
Failed object: 
"] 
  
Error in packet
Reason: (tooBig) Response message would have been too large.
Failed object: 
  
SNMP['/usr/bin/snmpget' '-M' '/opt/librenms/mibs' '-m' 'SNMPv2-TC:SNMPv2-MIB:IF-MIB:IP-MIB:TCP-MIB:UDP-MIB:NET-SNMP-VACM-MIB' '-v2c' '-c' 'COMMUNITY' '-OQXUte' '-Pu' 'udp:HOSTNAME:161' 'SNMPv2-MIB::snmpOutBadValues.0' 'SNMPv2-MIB::snmpOutGenErrs.0' 'SNMPv2-MIB::snmpOutGetRequests.0' 'SNMPv2-MIB::snmpOutGetNexts.0' 'SNMPv2-MIB::snmpOutSetRequests.0' 'SNMPv2-MIB::snmpOutGetResponses.0' 'SNMPv2-MIB::snmpOutTraps.0' 'SNMPv2-MIB::snmpSilentDrops.0' 'SNMPv2-MIB::snmpProxyDrops.0']  
Exitcode: 2 ["Error in packet
Reason: (tooBig) Response message would have been too large.
Failed object: 
"] 
  
Error in packet
Reason: (tooBig) Response message would have been too large.
Failed object: 
  
udp   
SNMP['/usr/bin/snmpget' '-M' '/opt/librenms/mibs' '-m' 'SNMPv2-TC:SNMPv2-MIB:IF-MIB:IP-MIB:TCP-MIB:UDP-MIB:NET-SNMP-VACM-MIB' '-v2c' '-c' 'COMMUNITY' '-OQXUte' '-Pu' 'udp:HOSTNAME:161' 'UDP-MIB::udpInDatagrams.0' 'UDP-MIB::udpOutDatagrams.0' 'UDP-MIB::udpInErrors.0' 'UDP-MIB::udpNoPorts.0']  
UDP-MIB::udpInDatagrams.0 = 12676534
UDP-MIB::udpOutDatagrams.0 = 12649263
UDP-MIB::udpInErrors.0 = 0
UDP-MIB::udpNoPorts.0 = 526
  
  
RRD[update /data/rrd/a.b.c.d/netstats-udp.rrd N:12676534:12649263:0:526]  
tcp   
SNMP['/usr/bin/snmpget' '-M' '/opt/librenms/mibs' '-m' 'SNMPv2-TC:SNMPv2-MIB:IF-MIB:IP-MIB:TCP-MIB:UDP-MIB:NET-SNMP-VACM-MIB' '-v2c' '-c' 'COMMUNITY' '-OQXUte' '-Pu' 'udp:HOSTNAME:161' 'TCP-MIB::tcpActiveOpens.0' 'TCP-MIB::tcpPassiveOpens.0' 'TCP-MIB::tcpAttemptFails.0' 'TCP-MIB::tcpEstabResets.0' 'TCP-MIB::tcpCurrEstab.0' 'TCP-MIB::tcpInSegs.0' 'TCP-MIB::tcpOutSegs.0' 'TCP-MIB::tcpRetransSegs.0' 'TCP-MIB::tcpInErrs.0' 'TCP-MIB::tcpOutRsts.0']  
Exitcode: 2 ["Error in packet
Reason: (tooBig) Response message would have been too large.
Failed object: 
"] 
  
Error in packet
Reason: (tooBig) Response message would have been too large.
Failed object: 
  
  
>> SNMP: [11/0.38s] MySQL: [0/0.00s] RRD: [4/0.00s]  
>> Runtime for poller module 'netstats': 0.3904 seconds with 22776 bytes  
RRD[update /data/rrd/a.b.c.d/poller-perf-netstats.rrd N:0.39039492607117]  
#### Unload poller module netstats ####
  
#### Load poller module hr-mib ####
  
Module enabled: Global + | OS   | Device   | Manual    
SNMP['/usr/bin/snmpget' '-v2c' '-c' 'COMMUNITY' '-OUQs' '-m' 'HOST-RESOURCES-MIB' '-M' '/opt/librenms/mibs' 'udp:HOSTNAME:161' 'hrSystemMaxProcesses.0' 'hrSystemProcesses.0' 'hrSystemNumUsers.0']
Exitcode: 2  
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: hrSystemMaxProcesses.0

Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: hrSystemProcesses.0

Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: hrSystemNumUsers.0  
  
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: hrSystemMaxProcesses.0

Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: hrSystemProcesses.0

Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: hrSystemNumUsers.0  

  
>> SNMP: [1/0.05s] MySQL: [0/0.00s] RRD: [1/0.00s]  
>> Runtime for poller module 'hr-mib': 0.0485 seconds with 2776 bytes  
RRD[update /data/rrd/a.b.c.d/poller-perf-hr-mib.rrd N:0.048548936843872]  
#### Unload poller module hr-mib ####
  
#### Load poller module ucd-mib ####
  
Module enabled: Global + | OS   | Device   | Manual    
SNMP['/usr/bin/snmpbulkwalk' '-v2c' '-c' 'COMMUNITY' '-OQUs' '-m' 'UCD-SNMP-MIB' '-M' '/opt/librenms/mibs' 'udp:HOSTNAME:161' 'systemStats']
  
  
SNMP['/usr/bin/snmpget' '-v2c' '-c' 'COMMUNITY' '-OQUs' '-m' 'UCD-SNMP-MIB' '-M' '/opt/librenms/mibs' 'udp:HOSTNAME:161' 'laLoadInt.1' 'laLoadInt.2' 'laLoadInt.3']
Exitcode: 2  
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: laLoadInt.1

Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: laLoadInt.2

Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: laLoadInt.3  
  
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: laLoadInt.1

Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: laLoadInt.2

Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: laLoadInt.3  
  
>> SNMP: [2/0.08s] MySQL: [0/0.00s] RRD: [1/0.00s]  
>> Runtime for poller module 'ucd-mib': 0.0809 seconds with 2952 bytes  
RRD[update /data/rrd/a.b.c.d/poller-perf-ucd-mib.rrd N:0.080852031707764]  
#### Unload poller module ucd-mib ####
  
#### Load poller module ipSystemStats ####
  
Module enabled: Global + | OS   | Device   | Manual    
SNMP['/usr/bin/snmpbulkwalk' '-v2c' '-c' 'COMMUNITY' '-OQUs' '-m' 'IP-MIB' '-M' '/opt/librenms/mibs' 'udp:HOSTNAME:161' 'ipSystemStats']
  
  

  
>> SNMP: [1/0.08s] MySQL: [0/0.00s] RRD: [1/0.00s]  
>> Runtime for poller module 'ipSystemStats': 0.0777 seconds with 1528 bytes  
RRD[update /data/rrd/a.b.c.d/poller-perf-ipSystemStats.rrd N:0.077715158462524]  
#### Unload poller module ipSystemStats ####
  
#### Load poller module ports ####
  
Module enabled: Global + | OS   | Device   | Manual    
SQL[SELECT *, `ports_statistics`.`port_id` AS `ports_statistics_port_id`, `ports`.`port_id` AS `port_id` FROM `ports` LEFT OUTER JOIN `ports_statistics` ON `ports`.`port_id` = `ports_statistics`.`port_id` WHERE `ports`.`device_id` = ? ORDER BY ports.port_id [3] 1.41ms] 
  
SNMP['/usr/bin/snmpbulkwalk' '-v2c' '-c' 'COMMUNITY' '-OQUs' '-m' 'IF-MIB' '-M' '/opt/librenms/mibs' 'udp:HOSTNAME:161' 'ifXEntry']
  
  
SNMP['/usr/bin/snmpbulkwalk' '-v2c' '-c' 'COMMUNITY' '-OQUst' '-m' 'IF-MIB' '-M' '/opt/librenms/mibs' 'udp:HOSTNAME:161' 'ifEntry']
ifIndex.1 = 1
ifDescr.1 = En
ifType.1 = ethernetCsmacd
ifMtu.1 = 1500
ifSpeed.1 = 0
ifPhysAddress.1 = c8:45:44:30:21:f
ifAdminStatus.1 = up
ifOperStatus.1 = up
ifLastChange.1 = 247101548
ifInOctets.1 = 0
ifInUcastPkts.1 = 0
ifInNUcastPkts.1 = 0
ifInDiscards.1 = 0
ifInErrors.1 = 0
ifInUnknownProtos.1 = 0
ifOutOctets.1 = 0
ifOutUcastPkts.1 = 0
ifOutNUcastPkts.1 = 0
ifOutDiscards.1 = 0
ifOutErrors.1 = 0
ifOutQLen.1 = 0
ifSpecific.1 = zeroDotZero  
  
SNMP['/usr/bin/snmpbulkwalk' '-v2c' '-c' 'COMMUNITY' '-OQUs' '-m' 'EtherLike-MIB' '-M' '/opt/librenms/mibs' 'udp:HOSTNAME:161' 'dot3StatsDuplexStatus']
  
  
SNMP['/usr/bin/snmpbulkwalk' '-v2c' '-c' 'COMMUNITY' '-OQUs' '-m' 'Q-BRIDGE-MIB' '-M' '/opt/librenms/mibs' 'udp:HOSTNAME:161' 'dot1qPvid']
  
  
Fetched data (Full ports polling): dot3StatsDuplexStatus   
array (
  1 => 
  array (
    'ifIndex' => '1',
    'ifDescr' => 'En',
    'ifType' => 'ethernetCsmacd',
    'ifMtu' => '1500',
    'ifSpeed' => '0',
    'ifPhysAddress' => 'c8:45:44:30:21:f',
    'ifAdminStatus' => 'up',
    'ifOperStatus' => 'up',
    'ifLastChange' => '247101548',
    'ifInOctets' => '0',
    'ifInUcastPkts' => '0',
    'ifInNUcastPkts' => '0',
    'ifInDiscards' => '0',
    'ifInErrors' => '0',
    'ifInUnknownProtos' => '0',
    'ifOutOctets' => '0',
    'ifOutUcastPkts' => '0',
    'ifOutNUcastPkts' => '0',
    'ifOutDiscards' => '0',
    'ifOutErrors' => '0',
    'ifOutQLen' => '0',
    'ifSpecific' => 'zeroDotZero',
  ),
)  
 valid  
ifInOctets  
ifOutOctets  
ifInUcastPkts  
ifOutUcastPkts  
ifInBroadcastPkts  
ifOutBroadcastPkts  
ifInMulticastPkts  
ifOutMulticastPkts  
ifSpeed (0)  
 Using ifDescr as ifAlias  
 Using ifDescr as ifName  

 ifInOctets (0 B) 0 Bps 248 secs  

 ifOutOctets (0 B) 0 Bps 248 secs  

 ifInErrors (0 B) 0 Bps 248 secs  

 ifOutErrors (0 B) 0 Bps 248 secs  

 ifInUcastPkts (0 B) 0 Bps 248 secs  

 ifOutUcastPkts (0 B) 0 Bps 248 secs  

 ifInNUcastPkts (0 B) 0 Bps 248 secs  

 ifOutNUcastPkts (0 B) 0 Bps 248 secs  

 ifInDiscards (0 B) 0 Bps 248 secs  

 ifOutDiscards (0 B) 0 Bps 248 secs  

 ifInUnknownProtos (0 B) 0 Bps 248 secs  

 ifInBroadcastPkts (0 B) 0 Bps 248 secs  

 ifOutBroadcastPkts (0 B) 0 Bps 248 secs  

 ifInMulticastPkts (0 B) 0 Bps 248 secs  

 ifOutMulticastPkts (0 B) 0 Bps 248 secs  
RRD warning: unused data sent ifInUcastPkts_rate  
RRD warning: unused data sent ifOutUcastPkts_rate  
RRD warning: unused data sent ifInErrors_rate  
RRD warning: unused data sent ifOutErrors_rate  
RRD warning: unused data sent ifInOctets_rate  
RRD warning: unused data sent ifOutOctets_rate  
RRD warning: unused data sent ifInBits_rate  
RRD warning: unused data sent ifOutBits_rate  
RRD[update /data/rrd/a.b.c.d/port-id271.rrd N:0:0:0:0:0:0:0:0:0:0:0:U:U:U:U]  
SQL[UPDATE `ports` set `ifSpeed_prev`=?,`ifInOctets`=?,`ifInOctets_prev`=?,`ifInOctets_rate`=?,`ifInOctets_delta`=?,`ifOutOctets`=?,`ifOutOctets_prev`=?,`ifOutOctets_rate`=?,`ifOutOctets_delta`=?,`ifInErrors`=?,`ifInErrors_prev`=?,`ifInErrors_rate`=?,`ifInErrors_delta`=?,`ifOutErrors`=?,`ifOutErrors_prev`=?,`ifOutErrors_rate`=?,`ifOutErrors_delta`=?,`ifInUcastPkts`=?,`ifInUcastPkts_prev`=?,`ifInUcastPkts_rate`=?,`ifInUcastPkts_delta`=?,`ifOutUcastPkts`=?,`ifOutUcastPkts_prev`=?,`ifOutUcastPkts_rate`=?,`ifOutUcastPkts_delta`=?,`poll_time`=?,`poll_prev`=?,`poll_period`=? WHERE `port_id` = ? ["0","0",0,0,0,"0",0,0,0,"0",0,0,0,"0",0,0,0,"0",0,0,0,"0",0,0,0,1757670494,1757670246,248,271] 9.65ms] 
  
SQL[UPDATE `ports_statistics` set `ifInNUcastPkts`=?,`ifInNUcastPkts_prev`=?,`ifInNUcastPkts_rate`=?,`ifInNUcastPkts_delta`=?,`ifOutNUcastPkts`=?,`ifOutNUcastPkts_prev`=?,`ifOutNUcastPkts_rate`=?,`ifOutNUcastPkts_delta`=?,`ifInDiscards`=?,`ifInDiscards_prev`=?,`ifInDiscards_rate`=?,`ifInDiscards_delta`=?,`ifOutDiscards`=?,`ifOutDiscards_prev`=?,`ifOutDiscards_rate`=?,`ifOutDiscards_delta`=?,`ifInUnknownProtos`=?,`ifInUnknownProtos_prev`=?,`ifInUnknownProtos_rate`=?,`ifInUnknownProtos_delta`=?,`ifInBroadcastPkts`=?,`ifInBroadcastPkts_prev`=?,`ifInBroadcastPkts_rate`=?,`ifInBroadcastPkts_delta`=?,`ifOutBroadcastPkts`=?,`ifOutBroadcastPkts_prev`=?,`ifOutBroadcastPkts_rate`=?,`ifOutBroadcastPkts_delta`=?,`ifInMulticastPkts`=?,`ifInMulticastPkts_prev`=?,`ifInMulticastPkts_rate`=?,`ifInMulticastPkts_delta`=?,`ifOutMulticastPkts`=?,`ifOutMulticastPkts_prev`=?,`ifOutMulticastPkts_rate`=?,`ifOutMulticastPkts_delta`=? WHERE `port_id` = ? ["0",0,0,0,"0",0,0,0,"0",0,0,0,"0",0,0,0,"0",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,271] 1.34ms] 
  
1 updated  
Port En: En (1 / #271)   VLAN = ? bps(0 bps/0 bps) bytes(0 B/0 B) pkts(0 pps/0 pps)   
SQL[update `ports` set `poll_time` = ?, `poll_prev` = ?, `poll_period` = ? where 0 = 1 [1757670494,1757670246,null] 0.62ms] 
  
0 updated  
  
>> SNMP: [4/0.26s] MySQL: [4/0.13s] RRD: [2/0.00s]  
>> Runtime for poller module 'ports': 0.3021 seconds with 34232 bytes  
RRD[update /data/rrd/a.b.c.d/poller-perf-ports.rrd N:0.30208492279053]  
#### Unload poller module ports ####
  
#### Load poller module customoid ####
  
Module enabled: Global + | OS   | Device   | Manual    
SQL[SELECT * FROM `customoids` WHERE `customoid_passed` = 1 AND `device_id` = ? [3] 0.89ms] 
  
  
>> SNMP: [0/0.00s] MySQL: [1/0.01s] RRD: [1/0.00s]  
>> Runtime for poller module 'customoid': 0.0042 seconds with 1912 bytes  
RRD[update /data/rrd/a.b.c.d/poller-perf-customoid.rrd N:0.0042328834533691]  
#### Unload poller module customoid ####
  
#### Load poller module bgp-peers ####
  
Module enabled: Global + | OS   | Device   | Manual    
SQL[SELECT * FROM `bgpPeers` AS B LEFT JOIN `vrfs` AS V ON `B`.`vrf_id` = `V`.`vrf_id` WHERE `B`.`device_id` = ? [3] 1.06ms] 
  
  
>> SNMP: [0/0.00s] MySQL: [1/0.01s] RRD: [1/0.00s]  
>> Runtime for poller module 'bgp-peers': 0.0087 seconds with 1904 bytes  
RRD[update /data/rrd/a.b.c.d/poller-perf-bgp-peers.rrd N:0.0087211132049561]  
#### Unload poller module bgp-peers ####
  
#### Load poller module ucd-diskio ####
  
Module enabled: Global + | OS   | Device   | Manual    
SNMP['/usr/bin/snmpbulkwalk' '-M' '/opt/librenms/mibs' '-m' 'SNMPv2-TC:SNMPv2-MIB:IF-MIB:IP-MIB:TCP-MIB:UDP-MIB:NET-SNMP-VACM-MIB' '-v2c' '-c' 'COMMUNITY' '-OQXUte' '-Pu' '-Os' 'udp:HOSTNAME:161' 'UCD-DISKIO-MIB::diskIOTable']  
  
  
SQL[select * from `ucd_diskio` where `ucd_diskio`.`device_id` = ? and `ucd_diskio`.`device_id` is not null [3] 0.91ms] 
  
  
>> SNMP: [1/0.04s] MySQL: [1/0.01s] RRD: [1/0.00s]  
>> Runtime for poller module 'ucd-diskio': 0.0482 seconds with 7192 bytes  
RRD[update /data/rrd/a.b.c.d/poller-perf-ucd-diskio.rrd N:0.048187017440796]  
#### Unload poller module ucd-diskio ####
  
#### Load poller module wireless ####
  
Module enabled: Global + | OS   | Device   | Manual    
SQL[select * from `wireless_sensors` where `wireless_sensors`.`device_id` = ? and `wireless_sensors`.`device_id` is not null [3] 0.96ms] 
  
  
>> SNMP: [0/0.00s] MySQL: [1/0.01s] RRD: [1/0.00s]  
>> Runtime for poller module 'wireless': 0.0056 seconds with 2592 bytes  
RRD[update /data/rrd/a.b.c.d/poller-perf-wireless.rrd N:0.0055508613586426]  
#### Unload poller module wireless ####
  
#### Load poller module ospf ####
  
Module enabled: Global + | OS   | Device   | Manual    
SQL[select * from `vrf_lite_cisco` where `vrf_lite_cisco`.`device_id` = ? and `vrf_lite_cisco`.`device_id` is not null [3] 0.88ms] 
  
Processes: SNMP['/usr/bin/snmpbulkwalk' '-M' '/opt/librenms/mibs' '-m' 'SNMPv2-TC:SNMPv2-MIB:IF-MIB:IP-MIB:TCP-MIB:UDP-MIB:NET-SNMP-VACM-MIB' '-v2c' '-c' 'COMMUNITY' '-OQXUt' '-Pu' '-Os' 'udp:HOSTNAME:161' 'OSPF-MIB::ospfGeneralGroup']  
  
  
SQL[delete from `ospf_instances` where `ospf_instances`.`device_id` = ? and `ospf_instances`.`device_id` is not null and `context_name` = ? and 1 = 1 [3,""] 0.74ms] 
  

Total processes: 0  
  
>> SNMP: [1/0.04s] MySQL: [2/0.02s] RRD: [1/0.00s]  
>> Runtime for poller module 'ospf': 0.0513 seconds with 76016 bytes  
RRD[update /data/rrd/a.b.c.d/poller-perf-ospf.rrd N:0.051281929016113]  
#### Unload poller module ospf ####
  
#### Load poller module ospfv3 ####
  
Module enabled: Global + | OS   | Device   | Manual    
SQL[select * from `ospfv3_instances` where `ospfv3_instances`.`device_id` = ? and `ospfv3_instances`.`device_id` is not null [3] 0.99ms] 
  
  
>> SNMP: [0/0.00s] MySQL: [1/0.01s] RRD: [1/0.00s]  
>> Runtime for poller module 'ospfv3': 0.0076 seconds with 4392 bytes  
RRD[update /data/rrd/a.b.c.d/poller-perf-ospfv3.rrd N:0.0076391696929932]  
#### Unload poller module ospfv3 ####
  
#### Load poller module entity-physical ####
  
Module enabled: Global + | OS   | Device   | Manual    
  
>> SNMP: [0/0.00s] MySQL: [0/0.00s] RRD: [1/0.00s]  
>> Runtime for poller module 'entity-physical': 0.0019 seconds with 1208 bytes  
RRD[update /data/rrd/a.b.c.d/poller-perf-entity-physical.rrd N:0.0018808841705322]  
#### Unload poller module entity-physical ####
  
#### Load poller module applications ####
  
Module enabled: Global + | OS   | Device   | Manual    
SQL[select * from `applications` where `applications`.`device_id` = ? and `applications`.`device_id` is not null and `applications`.`deleted_at` is null [3] 0.84ms] 
  
  
>> SNMP: [0/0.00s] MySQL: [1/0.01s] RRD: [1/0.00s]  
>> Runtime for poller module 'applications': 0.0078 seconds with 71288 bytes  
RRD[update /data/rrd/a.b.c.d/poller-perf-applications.rrd N:0.0077750682830811]  
#### Unload poller module applications ####
  
#### Load poller module stp ####
  
Module enabled: Global + | OS   | Device   | Manual    
SQL[select * from `stp` where `stp`.`device_id` = ? and `stp`.`device_id` is not null [3] 0.92ms] 
  
Instances: 
SQL[select * from `ports_stp` where `ports_stp`.`device_id` = ? and `ports_stp`.`device_id` is not null [3] 0.84ms] 
  
Ports: 
  
>> SNMP: [0/0.00s] MySQL: [2/0.02s] RRD: [1/0.00s]  
>> Runtime for poller module 'stp': 0.0082 seconds with 16056 bytes  
RRD[update /data/rrd/a.b.c.d/poller-perf-stp.rrd N:0.0081539154052734]  
#### Unload poller module stp ####
  
#### Load poller module ntp ####
  
Module enabled: Global + | OS   | Device   | Manual    
  
>> SNMP: [0/0.00s] MySQL: [0/0.00s] RRD: [1/0.00s]  
>> Runtime for poller module 'ntp': 0.0017 seconds with 1320 bytes  
RRD[update /data/rrd/a.b.c.d/poller-perf-ntp.rrd N:0.0016930103302002]  
#### Unload poller module ntp ####
  
RRD[update /data/rrd/a.b.c.d/poller-perf.rrd N:2.3892450332642]  
SQL[select * from `device_graphs` where `device_graphs`.`device_id` = ? and `device_graphs`.`device_id` is not null [3] 0.94ms] 
  
Enabled graphs (10): poller_modules_perf poller_perf ping_perf uptime availability netstat_icmp netstat_icmp_info netstat_ip netstat_ip_frag netstat_udp

  
SQL[update `devices` set `last_polled` = ?, `last_polled_timetaken` = ? where `device_id` = ? ["2025-09-12 10:48:14",2.38924503326416,3] 5.57ms] 
  

>>> Polled a.b.c.d (3) in 2.389 seconds <<<  
### Start Device Groups ###  
SQL[select * from `device_groups` [] 0.85ms] 
  
SQL[select * from `device_group_device` where `device_group_device`.`device_id` = ? [3] 0.59ms] 
  
Groups Added:   Removed:   
### End Device Groups (0.014s) ### 
  
#### Start Alerts ####  
SQL[select `device_groups`.*, `device_group_device`.`device_id` as `pivot_device_id`, `device_group_device`.`device_group_id` as `pivot_device_group_id` from `device_groups` inner join `device_group_device` on `device_groups`.`id` = `device_group_device`.`device_group_id` where `device_group_device`.`device_id` = ? [3] 0.83ms] 
  
SQL[select `behavior` from `alert_schedule` where (`start` <= ? and `end` >= ? and (`recurring` = ? or (`recurring` = ? and ((time(`start`) < time(`end`) and time(`start`) <= ? and time(`end`) > ?) or (time(`start`) > time(`end`) and (time(`start`) <= ? or time(`end`) > ?))) and (`recurring_day` like ? or `recurring_day` is null)))) and (exists (select * from `devices` inner join `alert_schedulables` on `devices`.`device_id` = `alert_schedulables`.`alert_schedulable_id` where `alert_schedule`.`schedule_id` = `alert_schedulables`.`schedule_id` and `alert_schedulables`.`alert_schedulable_type` = ? and `alert_schedulables`.`alert_schedulable_id` = ?) or exists (select * from `locations` inner join `alert_schedulables` on `locations`.`id` = `alert_schedulables`.`alert_schedulable_id` where `alert_schedule`.`schedule_id` = `alert_schedulables`.`schedule_id` and `alert_schedulables`.`alert_schedulable_type` = ? and `alert_schedulables`.`alert_schedulable_id` = ?)) limit 1 ["2025-09-12T09:48:14.753994Z","2025-09-12T09:48:14.753994Z",0,1,"09:48:14","09:48:14","09:48:14","09:48:14","%","device",3,"location",1] 1.4ms] 
  
SQL[select * from `devices` where `devices`.`device_id` = ? limit 1 [3] 0.96ms] 
  
SQL[SELECT DISTINCT a.* FROM alert_rules a
        LEFT JOIN alert_device_map d ON a.id=d.rule_id AND (a.invert_map = 0 OR a.invert_map = 1 AND d.device_id = ?)
        LEFT JOIN alert_group_map g ON a.id=g.rule_id AND (a.invert_map = 0 OR a.invert_map = 1 AND g.group_id IN (SELECT DISTINCT device_group_id FROM device_group_device WHERE device_id = ?))
        LEFT JOIN alert_location_map l ON a.id=l.rule_id AND (a.invert_map = 0 OR a.invert_map = 1 AND l.location_id IN (SELECT DISTINCT location_id FROM devices WHERE device_id = ?))
        LEFT JOIN devices ld ON l.location_id=ld.location_id AND ld.device_id = ?
        LEFT JOIN device_group_device dg ON g.group_id=dg.device_group_id AND dg.device_id = ?
        WHERE a.disabled = 0 AND (
            (d.device_id IS NULL AND g.group_id IS NULL AND l.location_id IS NULL)
            OR (a.invert_map = 0 AND (d.device_id=? OR dg.device_id=? OR ld.device_id=?))
            OR (a.invert_map = 1  AND (d.device_id != ? OR d.device_id IS NULL) AND (dg.device_id != ? OR dg.device_id IS NULL) AND (ld.device_id != ? OR ld.device_id IS NULL))
        ) [3,3,3,3,3,3,3,3,3,3,3] 3.67ms] 
  
Rule #1 (Device Down! Due to no ICMP response.):   
  
SQL[SELECT state FROM alerts WHERE rule_id = ? AND device_id = ? ORDER BY id DESC LIMIT 1 [1,3] 0.41ms] 
  
Status: NOCHG  
Rule #2 (Device Down (SNMP unreachable)):   
  
SQL[SELECT state FROM alerts WHERE rule_id = ? AND device_id = ? ORDER BY id DESC LIMIT 1 [2,3] 0.4ms] 
  
Status: NOCHG  
Rule #3 (Device rebooted):   
  
SQL[SELECT state FROM alerts WHERE rule_id = ? AND device_id = ? ORDER BY id DESC LIMIT 1 [3,3] 0.56ms] 
  
Status: NOCHG  
Rule #4 (Port status up/down):   
  
SQL[SELECT state FROM alerts WHERE rule_id = ? AND device_id = ? ORDER BY id DESC LIMIT 1 [4,3] 0.33ms] 
  
Status: NOCHG  
Rule #5 (Ping Latency):   
  
SQL[SELECT state FROM alerts WHERE rule_id = ? AND device_id = ? ORDER BY id DESC LIMIT 1 [5,3] 0.42ms] 
  
Status: NOCHG  
Rule #6 (Port utilisation over threshold):   
  
SQL[SELECT state FROM alerts WHERE rule_id = ? AND device_id = ? ORDER BY id DESC LIMIT 1 [6,3] 0.31ms] 
  
Status: NOCHG  
Rule #7 (Sensor over limit - Check Device Health Settings):   
  
SQL[SELECT state FROM alerts WHERE rule_id = ? AND device_id = ? ORDER BY id DESC LIMIT 1 [7,3] 0.38ms] 
  
Status: NOCHG  
Rule #8 (Sensor under limit - Check Device Health Settings):   
  
SQL[SELECT state FROM alerts WHERE rule_id = ? AND device_id = ? ORDER BY id DESC LIMIT 1 [8,3] 0.37ms] 
  
Status: NOCHG  
Rule #9 (Service up/down):   
  
SQL[SELECT state FROM alerts WHERE rule_id = ? AND device_id = ? ORDER BY id DESC LIMIT 1 [9,3] 0.32ms] 
  
Status: NOCHG  
Rule #12 (State Sensor Critical):   
  
SQL[SELECT state FROM alerts WHERE rule_id = ? AND device_id = ? ORDER BY id DESC LIMIT 1 [12,3] 0.29ms] 
  
Status: NOCHG  
#### End Alerts (0.0422s) ####
  

SNMP [24/1.06s]: Snmpget[16/0.61s] Snmpwalk[8/0.46s]  
SQL [62/0.72s]: Select[50/0.43s] Update[10/0.28s] Delete[2/0.01s]  
RRD [34/0.02s]: Update[34/0.02s]
```

**Comment by loqster** [comment]
This seams to come from the resources/definitions/os_detection/enlogic-pdu.yaml looking for firmware versions beginning with '1'

But all the old version nLogic PDUs that we have are firmware version '7.'  or '6' so it makes it not work because the discovery looks for devices with firmware versions starting with a '1.'

I have fixed it by modifying the bellow file like shown but it applys to our environment a more generic way might be better. 

resources/definitions/os_detection/enlogic-pdu.yaml

```
os: enlogic-pdu
type: power
text: 'enLogic PDU'
icon: enlogic
over:
    - { graph: device_voltage, text: Voltage }
    - { graph: device_current, text: Current }
    - { graph: device_power, text: Power }
mib_dir: enlogic
discovery:
    -   sysObjectID: .1.3.6.1.4.1.38446.
        snmpget:
          oid: ENLOGIC-PDU-MIB::pduNamePlateFirmwareVersion.1
          op: starts
          value: '7.'
    -   sysObjectID: .1.3.6.1.4.1.38446.
        snmpget:
          oid: ENLOGIC-PDU-MIB::pduNamePlateFirmwareVersion.1
          op: starts
          value: '6.'
```

**Comment by kate-james** [comment]
@loqster has this issue resolved with the merge of #18162?

**Comment by loqster** [comment]
If I remember correctly did not. The  #18245 worked better although still not discovering the old PDU's fully although mostly just the FW version and OS were wrong.

**Comment by murrant** [comment]
Something very strange in your discovery output...  You should have an snmpget request for 'SNMPv2-MIB::sysObjectID.0', 'SNMPv2-MIB::sysDescr.0', 'SNMPv2-MIB::sysName.0' in the core module.

But I don't see it there. It is not conditional, it should be run every time.

**Comment by loqster** [comment]
Apologies for the delay. Missed the response. 

This is what I'm getting no changes were made default images are pulled from the registry and deployed via compose. 

The only custom thing is in the config directory where I have configured LDAP for authentication.

**Comment by loqster** [comment]
Just a note with the latest version 26.1.1 discovery of both new and old PDUs seam to work fine. 

But after a while the values for 'Power' default to '0' for some reason and each subsequent poll gets these values as '0' going forward. 

Update-11-02

Had modified this file "/opt/librenms/resources/definitions/os_discovery/enlogic-pdu.yaml"

Like this:
```
librenms:/opt/librenms/resources/definitions/os_discovery$ diff enlogic-pdu.yaml enlogic-pdu.yaml-backup 
--- enlogic-pdu.yaml
+++ enlogic-pdu.yaml-backup
@@ -18,12 +18,12 @@
                 -
                     oid: ENLOGIC-PDU2-MIB::pduUnitStatusTable
                     value: ENLOGIC-PDU2-MIB::pduUnitStatusActivePower
-                    num_oid: '.1.3.6.1.4.1.38446.1.2.4.1.4.{{ $index }}'
+                    num_oid: '.1.3.6.1.4.1.38446.1.2.4.1.4.1.{{ $index }}'
                     descr: "Active power #{{ $index }}"
                 -
                     oid: ENLOGIC-PDU2-MIB::pduInputPhaseStatusTable
                     value: ENLOGIC-PDU2-MIB::pduInputPhaseStatusActivePower
-                    num_oid: '.1.3.6.1.4.1.38446.1.3.4.1.7.{{ $index }}'
+                    num_oid: '.1.3.6.1.4.1.38446.1.3.4.1.7.1.{{ $index }}'
                     index: 'pduInputPhaseStatusActivePower.{{ $index }}'
                     descr: "Input Phase #{{ $index }}"
         voltage:
```

This seam to have fixed the Power reading values but curious it works on version 26.1.1-r0 published on the 13th January but not version 26.1.1-r1 published 23rd January

Can pull additional logs or provide discovery / poll details / logs for these versions if required. 

Update-12-02

Missed the part where multiple containers used the same librenms image. 

By ensuring the modifications in the ..os_discovery/enlogic-pdu.yaml file are the same across all containers the discrepancy between versions was resolved.

**Comment by laf** [comment]
If this is still happening please re-open this but provide a full discovery and poller debug
