### ISSUE TITLE
Name/Desc/Alias based port mapping might fail due to constraint in database

### ISSUE THREAD

**Issue by BarbarossaTM** [librenms/librenms#3510]
Hi,

(This might be related to the problems raised at the end of issue #386, but it might as well be a separate problem, so I prefered opening another issue.)

I noticed a problem when polling ports based on there ifName/ifAlias and having some fluctuation in ifIndexes in between. Some ports aren't created in libreNMS.

Some debugging revealed that this is caused by an unique index formed in the ports table over the device_id and the ifIndex: 

```
SQL[INSERT INTO `ports` (`device_id`,`ifIndex`,`ifName`)  VALUES ('6','24','bb-wag-lnx01')]
ERROR 1062 (23000): Duplicate entry '6-24' for key 'device_ifIndex'
```

Using ifName/ifAlias/ifDescr because the ifIndex isn't stable on all devices (Linux boxes f.e.) this is a fundamental problem as the situation that an ifIndex is reused will occur. Updating the ifIndex in the database to the current one for every interface while polling might run into the same problem as there might be another interface having this ifIndex stored in the DB. This would only shift the problem into another race condition and isn't a solution.

One could argue that we ignore the ports for this poll when adding it to the DB failed, try to rename all the ifIndexes and hope for more luck next time, but this isn't really a solution either in my opinion.

Can anyone grasp what would happen/break/explose/set on fire when removing the device_ifIndex key?

@murrant suggested on IRC it might be an option to change the unique key to be on `device-ifIndex-ifName` which might be an option, but might fail again when ifName is NULL (which it is on some UBNT wifi devices).

So basicly I'd think it would be best to drop the unique key if there's no hidden pitfall anywhere around :)

Comments?

Best
Max

**Comment by BarbarossaTM** [comment]
So dropping this constraint revealed that I hid a bug in the discoverer, fixed in PR #3655 .
Besides that I did not see any problems after dropping the constraint. Will test this on another large install to verify.

Best
Max

**Comment by laf** [comment]
Feel free to submit a PR when you're ready :)

**Comment by patrick7** [comment]
Looks like the problem is still present, see https://github.com/librenms/librenms/issues/6006

**Comment by philmd** [comment]
same here...

Tagging @BarbarossaTM for comments.

**Comment by BarbarossaTM** [comment]
Hi,

yeah this utterly sounds like it's related.

I dropped the 

  UNIQUE KEY `device_ifIndex` (`device_id`,`ifIndex`)

constraint on table `ports` on one of my installs using ifName in a larger scale and it didn't break for me. You might want to try the same (at your own risk :)).

When this works for you, we should discuss including this as an SQL-update for future versions. @laf 

Best
Max

**Comment by patrick7** [comment]
Could you share the exact command to be sure I run the right thing? :-)

**Comment by patrick7** [comment]
I just ran 
`alter table ports drop index `device_ifIndex`;`

Let's see if it helps.

**Comment by murrant** [comment]
Another option could be to extend the index to include ifName

**Comment by patrick7** [comment]
If there are multiple ports with the same ifIndex in the database, where does librenms know from which interfaces should be shown? Also we need to make sure the link between IPs and Ports is always up to date.

**Comment by laf** [comment]
I think I'm all for dropping the index on this one. Although out of interest, Is this something that continues to happen or does poller remove the bad interface later on that poll run and the next poll run inserts the new port as expected?

**Comment by patrick7** [comment]
I removed the index and the interfaces are still not appearing.

**Comment by laf** [comment]
You need to provide all the debug info in this link: http://docs.librenms.org/Support/FAQ/#faq8

**Comment by murrant** [comment]
@laf I had one install where this index was missing (I might have removed it for testing) and when I went to re-add the index, there was conflicts.
One example is a device that was swapped out.  The old ports for this device in the database were causing things to not work as it was getting the wrong database entries for the ports.

**Comment by BarbarossaTM** [comment]
@murrant: Can you elaborate on the issue? I'm running at least two instance with the unique key drop without any noticeable problems here.

**Comment by murrant** [comment]
Add a device and let it discover/poll.  Now swap that device out with a different device with different ports and at least some overlapping ifIndexes.  The ports from the old device remain in the database.  This means whenever a port is looked up by device and ifIndex, it will get the old interfaces from the database, but the poller is only updating the new interfaces.  Anything that does a lookup by port_id works properly of course.

**Comment by laf** [comment]
I'm struggling to replicate this :(

Switched to ifName for port association, tried ifIndex, swapped the community on a device to two others (using snmpsimd) and in all situations the old ports were removed and new ones added.

**Comment by patrick7** [comment]
I had the problem when I added a new wireless nic to the machine. Or with openvswitch, when I create some interfaces / reboot the machine.

**Comment by patrick7** [comment]
I could give teamviewer access, however I do not have the time to collect and anonymize all the data.

**Comment by laf** [comment]
I'm closing this issue. It's not coming up in day to day issues for people and it's not had any feedback in over 6 months now.

**Comment by kdohBNY** [comment]
I'm not sure if it's related to this issue, but I'm having an issue with some devices and their port associations post OS/firmware upgrade on the network device. I have a group of Meraki MX devices that I've updated the firmware for and now the port associations are incorrect. If I downgrade the firmware back to the original version it was on when I first added the device into LibreNMS it corrects the issue. I also have the same issue if I swap a device for a different model but use the same IP I originally used to add the device to LibreNMS. For example: if I added a device with 192.168.1.1 and it was a Cisco2960x but then change the device with a Cisco3750 with less ports, all the ports from the 2960x still show up under "Port Settings" for the device. Removing the device and adding it back it does not correct the ports either.
