### ISSUE TITLE
Customize Port Name(s)

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms#5288]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ x] Please include all of the information between the `====================================` section of `./validate.php`.
- [ x] If you would like us to add a new device or your device is listed as Generic then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ x] Please provide as much detail as possible.

Hi,

Sorry if this is a dumb question, or if it's already answered / captured - I have been trying to track it down, no luck so far ... :(.

Is there a way to customize the port names on a device? For example ... enp6s6f0 doesn't mean much to me, but "PCI NIC" would ... ;-).

Thanks!

**Comment by laf** [comment]
You can already over ride the description in edit device -> port settings.

**Comment by arrmo** [comment]
Yep, I did find that - but it doesn't carry over to the various pages / properties. It's still names like enp6s6f0 to select to look at traffic (for example) ... and this is different for each machine ... :(

**Comment by laf** [comment]
Got an example page?

**Comment by arrmo** [comment]
You mean like this?
![image](https://cloud.githubusercontent.com/assets/8756384/21700696/5d9071fa-d367-11e6-8eaa-346f31e97634.png)

**Comment by murrant** [comment]
If you hover over the devices, you'll see full description.

**Comment by laf** [comment]
You can try and set this in config.php:

```php
unset($config['os']['OSNAME']['ifname']);
$config['os']['OSNAME']['ifalias'] = true;
```

Replace OSNAME with the actual os definition we have

**Comment by arrmo** [comment]
Hmmm .. sorry, trying to digest (understand) this - before I make the change and break something ... ;).

Where does ifalias come from? Or is it the description - meaning with this, the description is used?

Thanks!

**Comment by laf** [comment]
Try it, should only effect webui. ifalias is available in snmp and in webui that is what you are overriding.

**Comment by arrmo** [comment]
OK, tried it - didn't see any difference at all (and ran discovery and poller afterwards). Pretty sure it's me not quite understanding what this should do ... :-(.

Thanks!

**Comment by laf** [comment]
What did you put in your config?

**Comment by arrmo** [comment]
Exactly the code above, but OSNAME => windows. I think I'm missing where ifalias gets set?

**Comment by laf** [comment]
IfAlias is set either from the snmp response or you can override it in device -> edit -> ports -> description

**Comment by arrmo** [comment]
Hmmm ... OK, put the code (from above) back in config.php, and made sure device -> edit -> port settings -> description existed. But the names are still as above - so I assume this is not quite working?

Thanks!

**Comment by laf** [comment]
Try updating your install, this might have been a bug we fixed yesterday.

**Comment by arrmo** [comment]
No joy ... :(. Updated the install, sync'd to the latest code -> still seeing the non-friendly names.

Thoughts? Do I need to run discovery, or poller ... or something else I may be doing dumb?

Thanks!

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-customize-port-name-s/671
